name: Update Bing image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: 
      - 'script/crawler.py'
      - '.github/workflows/update.yml'
  schedule:
    # 15:00 every day Asia/Shanghai
    - cron: "0 7 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          cd script
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update image
        run: |
          export TZ=Asia/Shanghai
          cd script
          python crawler.py
        env:
          BOTTOKEN: ${{ secrets.BOTTOKEN }}
          CHANNELIDMAIN: ${{ secrets.CHANNELIDMAIN }}
          CHANNELIDARCHIEVE: ${{ secrets.CHANNELIDARCHIEVE }}
      
      - name: Move files to archieve
        run: |
          pwd
          mkdir archieve
          mv data archieve
          mv img archieve
      
      - name: Push archieves
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GIT_CONFIG_NAME: Bing Image Bot
          GIT_CONFIG_EMAIL: action@github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: archieve # The branch the action should deploy to.
          FOLDER: archieve # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          COMMIT_MESSAGE: Update Bing images.
