name: Update Bing image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: 
      - 'script/crawler.py'
      - '.github/workflows/update.yml'
  schedule:
    # 16:05 every day Asia/Shanghai
    - cron: "5 8 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          ref: data

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          cd script
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update image
        run: |
          export TZ=Asia/Shanghai
          cd script
          python crawler.py
        env:
          BOTTOKEN: ${{ secrets.BOTTOKEN }}
          CHANNELIDMAIN: ${{ secrets.CHANNELIDMAIN }}
          CHANNELIDARCHIEVE: ${{ secrets.CHANNELIDARCHIEVE }}
      - name: Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Bing Image Bot"
          git add data/* img/* -f
          git commit -m "Update Bing image." -a
          git push || echo "No changes to commit."
